DCist:
  id: 1
  url: https://dcist.com/topic/politics/
  states:
    - va
    - md
    - dc

Loudon Times:
  id: 2
  url: https://www.loudountimes.com/news/
  states:
    - va

Loudon Now:
  id: 3
  url: https://loudounnow.com/#
  states:
    - va

